const ICONS = {
  1: require("./Anti-Mage.webp"),
  2: require("./Axe.webp"),
  3: require("./Bane.webp"),
  4: require("./Bloodseeker.webp"),
  5: require("./Crystal_Maiden.webp"),
  6: require("./Drow_Ranger.webp"),
  7: require("./Earthshaker.webp"),
  8: require("./Juggernaut.webp"),
  9: require("./Mirana.webp"),
  10: require("./Morphling.webp"),
  11: require("./Shadow_Fiend.webp"),
  12: require("./Phantom_Lancer.webp"),
  13: require("./Puck.webp"),
  14: require("./Pudge.webp"),
  15: require("./Razor.webp"),
  16: require("./Sand_King.webp"),
  17: require("./Storm_Spirit.webp"),
  18: require("./Sven.webp"),
  19: require("./Tiny.webp"),
  20: require("./Vengeful_Spirit.webp"),
  21: require("./Windranger.webp"),
  22: require("./Zeus.webp"),
  23: require("./Kunkka.webp"),
  //   24: require("./.webp"),
  25: require("./Lina.webp"),
  26: require("./Lion.webp"),
  27: require("./Shadow_Shaman.webp"),
  28: require("./Slardar.webp"),
  29: require("./Tidehunter.webp"),
  30: require("./Witch_Doctor.webp"),
  31: require("./Lich.webp"),
  32: require("./Riki.webp"),
  33: require("./Enigma.webp"),
  34: require("./Tinker.webp"),
  35: require("./Sniper.webp"),
  36: require("./Necrophos.webp"),
  37: require("./Warlock.webp"),
  38: require("./Beastmaster.webp"),
  39: require("./Queen_of_Pain.webp"),
  40: require("./Venomancer.webp"),
  41: require("./Faceless_Void.webp"),
  42: require("./Wraith_King.webp"),
  43: require("./Death_Prophet.webp"),
  44: require("./Phantom_Assassin.webp"),
  45: require("./Pugna.webp"),
  46: require("./Templar_Assassin.webp"),
  47: require("./Viper.webp"),
  48: require("./Luna.webp"),
  49: require("./Dragon_Knight.webp"),
  50: require("./Dazzle.webp"),
  51: require("./Clockwerk.webp"),
  52: require("./Leshrac.webp"),
  53: require("./Natures_Prophet.webp"),
  54: require("./Lifestealer.webp"),
  55: require("./Dark_Seer.webp"),
  56: require("./Clinkz.webp"),
  57: require("./Omniknight.webp"),
  58: require("./Enchantress.webp"),
  59: require("./Huskar.webp"),
  60: require("./Night_Stalker.webp"),
  61: require("./Broodmother.webp"),
  62: require("./Bounty_Hunter.webp"),
  63: require("./Weaver.webp"),
  64: require("./Jakiro.webp"),
  65: require("./Batrider.webp"),
  66: require("./Chen.webp"),
  67: require("./Spectre.webp"),
  68: require("./Ancient_Apparition.webp"),
  69: require("./Doom.webp"),
  70: require("./Ursa.webp"),
  71: require("./Spirit_Breaker.webp"),
  72: require("./Gyrocopter.webp"),
  73: require("./Alchemist.webp"),
  74: require("./Invoker.webp"),
  75: require("./Silencer.webp"),
  76: require("./Outworld_Destroyer.webp"),
  77: require("./Lycan.webp"),
  78: require("./Brewmaster.webp"),
  79: require("./Shadow_Demon.webp"),
  80: require("./Lone_Druid.webp"),
  81: require("./Chaos_Knight.webp"),
  82: require("./Meepo.webp"),
  83: require("./Treant_Protector.webp"),
  84: require("./Ogre_Magi.webp"),
  85: require("./Undying.webp"),
  86: require("./Rubick.webp"),
  87: require("./Disruptor.webp"),
  88: require("./Nyx_Assassin.webp"),
  89: require("./Naga_Siren.webp"),
  90: require("./Keeper_of_the_Light.webp"),
  91: require("./Io.webp"),
  92: require("./Visage.webp"),
  93: require("./Slark.webp"),
  94: require("./Medusa.webp"),
  95: require("./Troll_Warlord.webp"),
  96: require("./Centaur_Warrunner.webp"),
  97: require("./Magnus.webp"),
  98: require("./Timbersaw.webp"),
  99: require("./Bristleback.webp"),
  100: require("./Tusk.webp"),
  101: require("./Skywrath_Mage.webp"),
  102: require("./Abaddon.webp"),
  103: require("./Elder_Titan.webp"),
  104: require("./Legion_Commander.webp"),
  105: require("./Techies.webp"),
  106: require("./Ember_Spirit.webp"),
  107: require("./Earth_Spirit.webp"),
  108: require("./Underlord.webp"),
  109: require("./Terrorblade.webp"),
  110: require("./Phoenix.webp"),
  111: require("./Oracle.webp"),
  112: require("./Winter_Wyvern.webp"),
  113: require("./Arc_Warden.webp"),
  114: require("./Monkey_King.webp"),
  //   115: require("./.webp"),
  //   116: require("./.webp"),
  //   117: require("./.webp"),
  //   118: require("./.webp"),
  119: require("./Dark_Willow.webp"),
  120: require("./Pangolier.webp"),
  121: require("./Grimstroke.webp"),
  //   122: require("./.webp"),
  123: require("./Hoodwink.webp"),
  //   124: require("./.webp"),
  //   125: require("./.webp"),
  126: require("./Void_Spirit.webp"),
  //   127: require("./.webp"),
  128: require("./Snapfire.webp"),
  129: require("./Mars.webp"),
  //   130: require("./.webp"),
  //   131: require("./.webp"),
  //   132: require("./.webp"),
  //   133: require("./.webp"),
  //   134: require("./.webp"),
  135: require("./Dawnbreaker.webp"),
  136: require("./Marci.webp"),
  137: require("./Primal_Beast.webp"),
};
export default ICONS;
